[package]
name = "day-01"
version = "0.1.0"
edition = "2021"
authors = ["Allan JARRY <jarry.allan@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
itertools = { workspace = true }
